name: Backup Repositories

on:
  schedule:
    - cron: '0 */2 * * *'  
  workflow_dispatch:
  
jobs:
  backup:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Backup Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
          
      - name: Clone ACL4SSR_ACL4SSR and Process All Branches
        run: |
          # Create temporary directory for cloning
          git clone https://github.com/ACL4SSR/ACL4SSR temp_repo
          cd temp_repo
          
          # Get all branch names
          branches=$(git branch -r | grep -v 'HEAD' | sed 's|origin/||g' | sed 's/^[ \t]*//')
          
          # Create main directory if it doesn't exist
          mkdir -p "../ACL4SSR(ACL4SSR)"
          
          # Process each branch
          for branch in $branches; do
            echo "Processing branch: $branch"
            git checkout $branch
            
            # Create branch directory and copy files
            mkdir -p "../ACL4SSR(ACL4SSR)/$branch"
            cp -r * "../ACL4SSR(ACL4SSR)/$branch/"
          done
          
          # Clean up temporary directory
          cd .. && rm -rf temp_repo
          
      - name: Update timestamp
        run: echo "Backup run at $(date)" > backup-timestamp.txt
        
      - name: Commit and Push Changes
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if git diff-index --quiet HEAD; then
            echo "No changes detected, adding timestamp file."
            echo "Backup run at $(date)" > backup-timestamp.txt
            git add backup-timestamp.txt
            git commit -m "$(date +'%Y-%m-%d %H:%M:%S')"
          else
            git commit -m "Automated backup $(date +'%Y-%m-%d %H:%M:%S')"
          fi
          git remote set-url origin https://x-access-token:${PAT}@github.com/smjcxf/pz.git
          git push origin main
