name: 同步源仓库openwrt
on:
  schedule:
    - cron: '1 0,15 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: 同步源仓库
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT || github.event.client_payload.PAT }}
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id || ! github.event.sender.id || github.actor == 'BlueSkyClouds'
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Check if destination branch exists
        id: check-branch
        run: |
          if git show-ref --verify --quiet refs/heads/openwrt; then
            echo "destination_branch_exists=true" >> $GITHUB_OUTPUT
          else
            echo "destination_branch_exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Create destination branch if not exists
        if: steps.check-branch.outputs.destination_branch_exists == 'false'
        run: |
          git checkout -b openwrt

      - name: sync scripts
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/shineTripodcat/Xiaomi-ax3000t-openwrt.git"
          source_branch: "main"
          destination_branch: "openwrt"
          github_token: ${{ secrets.PAT || github.event.client_payload.PAT }}    
